from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import uuid
import os

async def generate_patient_report(patient_id: str, period_days: int) -> str:
    """Generates a PDF and returns the local temp file path."""
    temp_path = f"/tmp/report_{uuid.uuid4()}.pdf"
    os.makedirs("/tmp", exist_ok=True)
    c = canvas.Canvas(temp_path, pagesize=letter)
    
    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, 760, "Alz-AI Clinical Patient Report")
    c.setFont("Helvetica", 10)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(50, 742, f"Generated for Patient ID: {patient_id}  |  Period: Last {period_days} days")
    c.line(50, 735, 560, 735)

    # Section: Summary
    c.setFillColorRGB(0, 0, 0)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 715, "Summary")
    c.setFont("Helvetica", 11)
    c.drawString(50, 698, "Alzheimer's Stage: Level 2  |  Language: English")
    
    # Section: Medication
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 675, "Medication Adherence")
    c.setFont("Helvetica", 11)
    c.drawString(50, 658, "  Donepezil 10mg:   85% adherence")
    c.drawString(50, 643, "  Memantine 20mg:   90% adherence")
    
    # Section: Mood
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 620, "Mood Trend Analysis")
    c.setFont("Helvetica", 11)
    c.drawString(50, 603, "  Overall trend: Stabilizing")
    c.drawString(50, 588, "  Pattern: Increased confusion in evenings (Sundowning detected)")
    
    # Section: Alerts
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 565, "Alert History")
    c.setFont("Helvetica", 11)
    c.drawString(50, 548, f"  3 Priority-3 alerts in the last {period_days} days")
    c.drawString(50, 533, "  No missed appointments")
    
    # Section: AI Insights
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, 510, "AI Insights (High Confidence)")
    c.setFont("Helvetica", 11)
    c.drawString(50, 493, "  Donepezil adherence dropped to 60% this week. Consider morning dosing.")
    c.drawString(50, 478, "  SAATHI conversations improved average mood by 15%.")

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColorRGB(0.5, 0.5, 0.5)
    c.drawString(50, 50, "Generated by Alz-AI Platform. Strictly Confidential. For clinical use only.")
    
    c.showPage()
    c.save()

    return temp_path
