from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import uuid
import os
from app.services.cloudinary_service import upload_file

async def generate_patient_report(patient_id: str, period_days: int):
    temp_path = f"/tmp/report_{uuid.uuid4()}.pdf"
    os.makedirs("/tmp", exist_ok=True)
    c = canvas.Canvas(temp_path, pagesize=letter)
    
    # 1) Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 750, f"Alz-AI Patient Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, 730, f"Patient ID: {patient_id}")
    
    # 2) Summary
    c.drawString(50, 700, "Level: 2 | Language: English")
    
    # 3) Med Adherence
    c.drawString(50, 670, "Medication Adherence: Donepezil (85%), Memantine (90%)")
    
    # 4) Mood Trend
    c.drawString(50, 640, "Mood Trend: Stabilizing")
    
    # 5) Alerts
    c.drawString(50, 610, "Alert History: 3 Priority-3 alerts last 30 days")
    
    # 6) Appointments
    c.drawString(50, 580, "No missed appointments.")
    
    # 7) AI Insights
    c.drawString(50, 550, "AI Insight (High Conf): Donepezil adherence 60% this week. Consider morning dosing.")
    
    # 8) Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Alz-AI. Confidential.")
    
    c.showPage()
    c.save()
    
    folder = f"reports/{patient_id}"
    url = await upload_file(temp_path, folder=folder, resource_type="auto") 
    public_id = url.split('/')[-1].split('.')[0] # Hacky extracion for Signed URL compatibility 
    
    if os.path.exists(temp_path):
        os.remove(temp_path)
        
    return url, f"{folder}/{public_id}"
