"""add_cloned_voice_id_to_patient

Revision ID: 1fab53918d92
Revises: 9837c66bd116
Create Date: 2026-04-23 15:17:18.026774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fab53918d92'
down_revision = '9837c66bd116'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cloned_voice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'cloned_voice_id')
    # ### end Alembic commands ###
