"""add_voice_sample_url_to_patients

Revision ID: 9837c66bd116
Revises: 001b2fa19025
Create Date: 2026-04-23 11:32:17.029455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9837c66bd116'
down_revision = '001b2fa19025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('voice_sample_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'voice_sample_url')
    # ### end Alembic commands ###
